apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlists-recommender-deployment
  labels:
    app: playlists-recommender-giuliacastro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlists-recommender-giuliacastro
  template:
    metadata:
      labels:
        app: playlists-recommender-giuliacastro
    spec:
      containers:
      - name: playlists-recommender-giuliacastro
        image: playlists-recommender-giuliacastro:latest
        ports:
        - containerPort: 52025
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: project2-pv-giuliacastro
          mountPath: /home/giuliacastro/project2-pv
      - name: frequent-itemsets-giuliacastro
        image: frequent-itemsets-giuliacastro:latest
        volumeMounts:
        - name: project2-pv-giuliacastro
          mountPath: /home/giuliacastro/project2-pv
      volumes:
      - name: project2-pv-giuliacastro
        persistentVolumeClaim:
          claimName: project2-pv-giuliacastro
