apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlists-recommender-deployment
  labels:
    app: playlists-recommender-giuliacastro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlists-recommender-giuliacastro
  template:
    metadata:
      labels:
        app: playlists-recommender-giuliacastro
    spec:
      containers:
      - name: playlists-recommender-giuliacastro
        image: public.ecr.aws/u7i7l2e7/playlists-recommender-giuliacastro:v0.2
        ports:
        - containerPort: 52025
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: project2-pv-giuliacastro
          mountPath: /home/giuliacastro/project2-pv2
      - name: frequent-itemsets-giuliacastro
        image: public.ecr.aws/u7i7l2e7/frequent-itemsets-giuliacastro:v0.2
        volumeMounts:
        - name: project2-pv-giuliacastro
          mountPath: /home/giuliacastro/project2-pv2
      volumes:
      - name: project2-pv-giuliacastro
        persistentVolumeClaim:
          claimName: project2-pv-giuliacastro
          
