apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv-giuliacastro
  namespace: giuliacastro
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 1Gi 
  storageClassName: default-storage-class-giuliacastro
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      namespace: giuliacastro
hostPath:
  /home/giuliacastro/project2-pv2