apiVersion: v1
kind: Service
metadata:
  name: playlists-recommender-service
spec:
  selector:
    app: playlists-recommender-giuliacastro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 52025
      nodePort: 30001
  type: NodePort
