FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app

COPY playlist-recommendation/generate_rules_recommender.py /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "generate_rules_recommender.py"]