FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app

COPY playlist-recommendation/app.py /app
COPY playlist-recommendation/templates/index.html /app/templates/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 52025

ENV FLASK_APP=app.py

ENV FLASK_ENV=development

CMD ["flask", "run", "--host=0.0.0.0", "--port=52025"]